### PR TITLE
seperated scores by game mode

### PR DESCRIPTION
**Pull request by Agam642**
- Added option to select mode on scores menu
- Added new playerprefs for each game mode
- scores should now correspond to each game mode

Future:
- will add ability to enter name on game launch and then display name beside score (tentative if time permits)

### CODE REVIEW

**Review by danielkim10 — DISMISSED** [review]
Please review
image

**Comment by Agam642** [comment]
i dont see that

**Comment by danielkim10** [comment]
For the one operator scores I think you should specify which type of operator the score was achieved on by either putting the name of the operator next to the score or tracking the top 5 scores for each operator (ie 20 high scores spread across 4 tables)

**Comment by Agam642** [comment]
> For the one operator scores I think you should specify which type of operator the score was achieved on by either putting the name of the operator next to the score or tracking the top 5 scores for each operator (ie 20 high scores spread across 4 tables)

- but then i would not be able to implement the player name feature

**Comment by danielkim10** [comment]
How about making a high score table for each operator then :)

**Review by danielkim10 — APPROVED** [review]

**Pull request merged**
