### PR TITLE
added user name function

### PR DESCRIPTION
**Pull request by Agam642**
- Added ability to change name in settings menu
- user name is displayed in main menu in top left
- default value is "USER" 
- the set username screen needs some fixing in terms of ui can you guys adjust the text to your liking to correspond with the app

### CODE REVIEW

**Review by Raymond-Xia — CHANGES_REQUESTED** [review]
You can just use the character limit property in the input field component to limit it to 4 characters, then you don't have to do substring stuff.
Also, this comes up when I navigate back to the menu after entering an empty username:
image

**Comment by danielkim10** [comment]
Also please add some feedback text above the box that informs the user that their new name is saved.

**Comment by Raymond-Xia** [comment]
> Also please add some feedback text above the box that informs the user that their new name is saved.

It should also clear the text box after you've clicked enter.

**Comment by Agam642** [comment]
Where do I fi

> You can just use the character limit property in the input field component to limit it to 4 characters, then you don't have to do substring stuff. Also, this comes up when I navigate back to the menu after entering an empty username: image

how do i limit the text field?

**Review by Raymond-Xia — APPROVED** [review]
Still need to do UI improvements but I can do those after the feature is done

**Pull request merged**
